### ISSUE TITLE
#SpringData# string to jodaTime 需要配置一下

### ISSUE THREAD

**Issue by psycoHo** [psycoHo/issues#2]
```
jpa:

  properties:
    jadira:
      usertype:
        autoRegisterUserTypes: true
        databaseZone: UTC
        javaZone: UTC

```
